---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: {{ .Values.gateway.selector }}
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.hostname }}