---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
    spec:
      type: {{ .Values.service.type }}
      ports:
        {{- if .Values.containerPorts.http }}
        - name: http
        port: {{ .Values.service.ports.http }}
      selector: 
        app: nginx
  