---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.gateway.hostname }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: nginx-service
        port:
          number: 8080
